_schema: _schema
paths:
  uploads: public/images
  static: public
collections_config:
  pages:
    path: src/content/pages
    glob:
      - '!404.md'
    name: Pages
    icon: wysiwyg
    url: /[slug]/
    disable_url: false
    description: ''
    _editables:
    _enabled_editors:
      - visual
      - content
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    name: Blog
    icon: event_available
    url: /blog/[slug]/
    disable_url: false
    description: ''
    _editables:
      content:
        allow_custom_markup: false
        remove_custom_markup: false
        blockquote: true
        bold: true
        bulletedlist: true
        center:
        code: true
        copyformatting: true
        embed: true
        expandable:
        format: p, h2, h3, h4, h5, h6
        height:
        horizontalrule: true
        image: true
        image_size_attributes: true
        indent: true
        italic: true
        justify:
        left:
        link: true
        mime_type:
        numberedlist: true
        outdent: true
        paths:
        redo: true
        removeformat: true
        resize_style:
        right:
        snippet: true
        strike: true
        styles:
        subscript: true
        superscript: true
        table: true
        underline: true
        undo: true
        width:
    _enabled_editors:
      - content
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.mdx
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: false
        name: Post
        icon: newspaper
        preview:
        _editables:
        _enabled_editors:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
_inputs:
  answer:
    type: markdown
    cascade: true
  contacts[*]:
    type: markdown
    cascade: true
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false

_snippets:
  button:
    template: mdx_component
    inline: false
    preview:
      icon: smart_button
      text: Button
    definitions:
      component_name: ShortcodesButton
      named_args:
        - editor_key: label
          source_key: label
          type: string
        - editor_key: link
          source_key: link
          type: string
        - editor_key: style
          source_key: style
          type: string
        - editor_key: rel
          source_key: rel
          type: string
    _inputs:
      style:
        type: select
        options: 
          values:
            - outline
            - filled
      rel:
        type: select
        options: 
          values:
            - follow
            - nofollow